MIPS: Loongson: Register platoform driver for loongson2_cpufreq
Mads reported:

--------------
And, what's the deal with CONFIG_LOONGSON2_CPUFREQ? I had to go into
loongson2_cpufreq.c and comment out line 145 to 150 to compile the kernel
without warnings...

//static struct platform_device_id platform_device_ids[] = {
//  {
//      .name = "l2_cpufreq",
//  },
//  {}
//};

If I don't do that, this error occurs:

 CC      arch/mips/kernel/cpufreq/loongson2_cpufreq.o
cc1: warnings being treated as errors
arch/mips/kernel/cpufreq/loongson2_cpufreq.c:145:34: error: ‘platform_device_ids’ defined but not used
make[3]: *** [arch/mips/kernel/cpufreq/loongson2_cpufreq.o] Error 1
make[2]: *** [arch/mips/kernel/cpufreq] Error 2
make[1]: *** [arch/mips/kernel] Error 2
make: *** [arch/mips] Error 2
------------

The cause is I forgot registering the platform driver for loongson2, add
it.

Reported-by: Mads <mads@ab3.no>
Signed-off-by: Wu Zhangjin <wuzhangjin@gmail.com>

Signed-off-by: Wu Zhangjin <wuzhangjin@gmail.com>