MIPS: IP22, IP28: Fix build.
Broken by f6dc800f371f8936f5f40cd9d0da694c49bd6af3 "die() does not call
die notifier chain":

  CC      arch/mips/sgi-ip22/ip22-berr.o
cc1: warnings being treated as errors
/home/ralf/src/linux/upstream-linus/arch/mips/sgi-ip22/ip22-berr.c: In function ‘ip22_be_interrupt’:
/home/ralf/src/linux/upstream-linus/arch/mips/sgi-ip22/ip22-berr.c:100: error: passing argument 2 of ‘die_if_kernel’ discards qualifiers from pointer target type
/home/ralf/src/linux/upstream-linus/arch/mips/include/asm/ptrace.h:147: note: expected ‘struct pt_regs *’ but argument is of type ‘const struct pt_regs *’
make[3]: *** [arch/mips/sgi-ip22/ip22-berr.o] Error 1

and:

  CC      arch/mips/sgi-ip22/ip28-berr.o
cc1: warnings being treated as errors
/home/ralf/src/linux/upstream-linus/arch/mips/sgi-ip22/ip28-berr.c: In function ‘ip22_be_interrupt’:
/home/ralf/src/linux/upstream-linus/arch/mips/sgi-ip22/ip28-berr.c:462: error: passing argument 2 of ‘die_if_kernel’ discards qualifiers from pointer target type
/home/ralf/src/linux/upstream-linus/arch/mips/include/asm/ptrace.h:147: note: expected ‘struct pt_regs *’ but argument is of type ‘const struct pt_regs *’
make[3]: *** [arch/mips/sgi-ip22/ip28-berr.o] Error 1

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit 6ca903d0c2d8ace1ab91df470b78f2b3a72e9677)