MIPS: Big Sur: Fix build error due to merge mistake.
  CC      arch/mips/sibyte/bcm1480/smp.o
cc1: warnings being treated as errors
/home/ralf/src/linux/linux-queue/arch/mips/sibyte/bcm1480/smp.c: In function ‘bcm1480_mailbox_interrupt’:
/home/ralf/src/linux/linux-queue/arch/mips/sibyte/bcm1480/smp.c:181: error: unused variable ‘irq’
make[3]: *** [arch/mips/sibyte/bcm1480/smp.o] Error 1

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>